### PR TITLE
image converted into different color spaces

### PR DESCRIPTION
**Pull request by ashwanisng**
image converted into 

- [x]  BGR

- [x]  Gray Scale

- [x]  HSV

- [x]  HSL

### CODE REVIEW

**Comment by Anujg935** [comment]
great work @ashwanisng but I would suggest you to make different functions for all 4 conversions,that take a RGB image as input parameter and return converted image. It will be helpful in latter part of the project. 
So kindly do the changes and let me know.

**Comment by ashwanisng** [comment]
> great work @ashwanisng but I would suggest you to make different functions for all 4 conversions,that take a RGB image as input parameter and return converted image. It will be helpful in latter part of the project.
> So kindly do the changes and let me know.
 
Thanks for reviewing :)
did I have to make a function for all like this or make 4 different functions for all?

`def orignal(orignalImage):
    img_gray = plt.imshow(orignal_rgb[:,:,1], cmap="gray" , interpolation=None)
    img_hsl = cv.cvtColor(orignal_rgb, cv.COLOR_BGR2HLS)
    img_hsv = cv.cvtColor(images, cv.COLOR_BGR2HSV)
    plt.imshow(img_hsl)
    plt.imshow(orignal_rgb)
    plt.imshow(img_hsv)
        

orignal(img_hsv)
orignal(img_hsl)
orignal(img_gray)
orignal(orignal_rgb)`

**Comment by Anujg935** [comment]
you have to make 4 different function with relevant names like rgb_to_gray or something like that.

**Comment by ashwanisng** [comment]
okay I got it thanks @Anujg935

**Comment by ashwanisng** [comment]
@Anujg935  make some changes. Please review 👍

**Pull request merged**
