### PR TITLE
Environment section added.

### LINKED ISSUE #59: Adding Environment details in ISSUE_TEMPLATE.md
**Is your feature request related to a problem? Please describe.**
Without knowing the exact environment details it is hard to reproduce the error to rectify it.

**Describe the solution you'd like**
To add an environment Section in the ISSUE_TEMPLATE.md

**Describe alternatives you've considered**

**Approach to be followed (optional)**
Adding the environment section in which the user has to provide:
OS details
pip version
python version

**Additional context**

### PR DESCRIPTION
**Pull request by Purvanshsingh**
## Description

Added Environment Details Section in ISSUE_TEMPLATE.md

Fixes #59

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 image| image|

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
are you a dwoc participant?

**Comment by Purvanshsingh** [comment]
@akshitagupta15june Please review the pull request.

**Comment by Purvanshsingh** [comment]
> are you a dwoc participant?

yes participated in SWOC.

**Comment by akshitagupta15june** [comment]
ok i will be merging it if i will get full guidelines of swoc to how to points your pr.

**Comment by akshitagupta15june** [comment]
I have approved it

**Comment by Purvanshsingh** [comment]
Can I add the same for Bug_Report.md ?

**Comment by akshitagupta15june** [comment]
ok you can add it

**Review by akshitagupta15june — APPROVED** [review]

**Review by akshitagupta15june — APPROVED** [review]

**Pull request merged**
