### PR TITLE
Issue #81 : Show FPS on the side of frame

### PR DESCRIPTION
**Pull request by TanweerulHaque**
This is wrt to the issue #81 : Showing FPS on the side of frame -
1) Importing of 2 additional packages in this python file - "datetime" and "imutils"
2) Added the  FPS to be displayed in the "main" function definition of this file

### CODE REVIEW

**Comment by TanweerulHaque** [comment]
@akshitagupta15june This is wrt to the issue #81 : Showing FPS on the side of frame. I have briefly explained and done all the necessary changes. PR has been sent, Do merge it. Please guide me if there's anything wrong. Thank you.

**Comment by q-viper** [comment]
Hi @TanweerulHaque I just went through your [this](https://github.com/TanweerulHaque/lane_detection_opencv/blob/master/lanedetect_video_opencv.py) python file and figured out that you have used OpenCV as cv2 and cv somewhere. Please look at that. Use only cv2 or cv. FPS is shown good and after your correction to OpenCV importing, we are good to go.

**Comment by TanweerulHaque** [comment]
Sorry for the typo @q-viper . I have corrected it now. Thank you.

**Comment by q-viper** [comment]
You have done right but please look at this [article](https://www.geeksforgeeks.org/python-displaying-real-time-fps-at-which-webcam-video-file-is-processed-using-opencv/) too.

**Comment by akshitagupta15june** [comment]
ok!
Thankyou so much @q-viper  mentor for reviewing the pr.
I am merging your pr @TanweerulHaque

**Pull request merged**
