### PR TITLE
Edge detection in image is added

### PR DESCRIPTION
**Pull request by bharath-acchu**
Please review this PR
Different Edge detection is made 
This includes:
1. Laplacian method
2. sobel method 
3. canny edge detection

### CODE REVIEW

**Comment by Anujg935** [comment]
hi @bharath-acchu I have seen your PR but why are you changing multiple files for 1 single issue I don't know, it will be very difficult for us to account for that many files by every participant.
Now coming back to edge detection, it's good you have tried to use laplacian method but why are you using the Sobel method on top of the laplacian method, and because of that, we are not getting the results of soble method correctly. SO please make it separate.

**Comment by Anujg935** [comment]
Please update the PR and let me know.

**Comment by bharath-acchu** [comment]
Sorry for creating multiple files . It wont repeat in future . 
Sobel method is applied separately . It is not involved  with laplacian please look into again. laplacian image is not passed into sobel, gaussian image is passed so i think it is not involved with laplacian , please look into again.

**Comment by bharath-acchu** [comment]
I have made the necessary changes please look into it.

**Comment by Anujg935** [comment]
@bharath-acchu Great work 👍

**Pull request merged**
