### PR TITLE
Added probabilistic hough transform details

### PR DESCRIPTION
**Pull request by rsrkpatwari1234**
Fixing #77

### CODE REVIEW

**Comment by rsrkpatwari1234** [comment]
@akshitagupta15june please review my PR and update my score for issue generation and PR in njack iit patna.

**Comment by akshitagupta15june** [comment]
Hi this pr cant

**Comment by akshitagupta15june** [comment]
HI this pr cant be merged

**Comment by akshitagupta15june** [comment]
because there was not a feature improvement in project

**Pull request closed without merging**
