### PR TITLE
read and displayed images

### PR DESCRIPTION
**Pull request by bharath-acchu**

### CODE REVIEW

**Comment by Anujg935** [comment]
Hi, good work just a suggestion read the image using opencv cv2, as openCv is backbone of this project. good work.

**Comment by bharath-acchu** [comment]
Thank you for the suggestion , should I change and raise PR again?

**Comment by Anujg935** [comment]
Yes

**Comment by bharath-acchu** [comment]
I have committed changes please look into. And Please remove the previous PR. Thank you

**Pull request closed without merging**
