### PR TITLE
Selecting area of interest is added

### PR DESCRIPTION
**Pull request by bharath-acchu**
Please review my PR:
Here how area of interest is added and how it affects before and after canny edge detection is also shown

### CODE REVIEW

**Comment by Anujg935** [comment]
Hi @bharath-acchu  please update your previous PRS and files structure after that I will review this PR.

**Comment by Anujg935** [comment]
@bharath-acchu can you try to increase ROI vertically.

**Comment by bharath-acchu** [comment]
PR is updated, Please look into it

**Comment by Anujg935** [comment]
@bharath-acchu great work keep going 👍

**Review by Anujg935 — COMMENTED** [review]
good work

**Pull request merged**
