### PR TITLE
Create CODE_OF_CONDUCT.md issue #51

### PR DESCRIPTION
**Pull request by Tejas1510**
I have added the Code of Conduct File Which Fixes issue #51

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Great!
Are u a nwoc participant?

**Comment by Tejas1510** [comment]
@akshitagupta15june yes I am a nwoc participant

**Comment by Tejas1510** [comment]
@akshitagupta15june Can you please update the leaderboard with points associated with the merged PR

**Comment by akshitagupta15june** [comment]
Yes i will update it

**Pull request merged**
