### PR TITLE
canny edge detection added to the image

### PR DESCRIPTION
**Pull request by ashwanisng**

### CODE REVIEW

**Comment by Anujg935** [comment]
Hi @ashwanisng the issue is to use multiple edge detection techniques but you have only completed canny edge detection. Please complete the task and let me know.

**Comment by ashwanisng** [comment]
updated the file. please review @Anujg935 @akshitagupta15june 

- [x]  Laplacian

- [x]  sobel operator

- [x]  canny edge detection

**Comment by Anujg935** [comment]
great work 👍

**Review by Anujg935 — COMMENTED** [review]
Great work

**Review by akshitagupta15june — COMMENTED** [review]
GReat work @ashwanisng

**Comment by ashwanisng** [comment]
Thanks 😃 @akshitagupta15june @Anujg935

**Pull request closed without merging**
