### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by Pranav016**
Solves issue #56 

Improved the readme by adding NWoC banner and colored badges.

This PR was made under **NWoC**

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
@Pranav016 i cant see the nwoc banner.
i think there is some error.

**Comment by Pranav016** [comment]
> @Pranav016 i cant see the nwoc banner.
> i think there is some error.

I mean I add the NWoC info and the NWoC logo.

**Comment by akshitagupta15june** [comment]
yeah nwoc logo is not available/visible

**Comment by Pranav016** [comment]
> yeah nwoc logo is not available

Binary files like images can't be seen on github Pull requests if thats what you are asking. You can save it and it'll be visible. I'll give you a preview to help you review 😄 


image

**Comment by akshitagupta15june** [comment]
got it am merging it.

**Comment by akshitagupta15june** [comment]
still i cant see after merging.

**Comment by akshitagupta15june** [comment]
image

**Comment by akshitagupta15june** [comment]
@Pranav016 please see the issue

**Comment by Pranav016** [comment]
> @Pranav016 please see the issue

Fixed issue by #58

**Pull request merged**
